vim.cmd("colorscheme neodark") --colourscheme
-- vim.cmd("colorscheme neodarker") --colourscheme

local utils = require("main.general.utils")

local palette = {
	none = "NONE",
	fg = "#abb2bf",
	fg_1 = "#c5cad4",
	bg = "#0b1b3b",
	bg_1 = "#12151b",
	bg_2 = "#0e0f12",
	black = "#181a1f",
	black_1 = "#1f1f25",
	green = "#98c379",
	green_1 = "#89b06d",
	white = "#dedede",
	white_1 = "#afb2bb",
	white_2 = "#c9c9c9",
	blue = "#61afef",
	blue_1 = "#40d9ff",
	blue_2 = "#15181f",
	orange = "#d19a66",
	orange_1 = "#ff9640",
	orange_2 = "#ff8800",
	yellow = "#e5c07b",
	yellow_1 = "#ebae34",
	yellow_2 = "#d1b071",
	yellow_cursorline = "#fbfb00",
	red = "#e06c75",
	red_1 = "#ec5f67",
	red_2 = "#ffbba6",
	red_3 = "#cc626a",
	grey = "#5c6370",
	grey_1 = "#4b5263",
	grey_2 = "#777d86",
	grey_3 = "#282c34",
	grey_4 = "#2c323c",
	grey_5 = "#3e4452",
	grey_6 = "#3b4048",
	grey_7 = "#5c5c5c",
	grey_8 = "#1d2027",
	grey_9 = "#787e87",
	grey_10 = "#D3D3D3",
	gold = "#ffcc00",
	cyan = "#56b6c2",
	purple = "#c678dd",
	purple_highlight = "#bf40bf",
	unlisted = "#40e0d0",
}

local style = {
	none = "none",
	bold = "bold",
	italic = "italic",
}

local theme = {}

theme.base = {
	Normal = { fg = palette.fg, bg = palette.bg },
	Comment = { fg = palette.grey_2, bg = palette.none },
	Constant = { fg = palette.yellow, bg = palette.none },
	String = { fg = palette.green, bg = palette.none },
	Character = { fg = palette.green, bg = palette.none },
	Number = { fg = palette.orange, bg = palette.none },
	Boolean = { fg = palette.blue, bg = palette.none },
	Float = { fg = palette.yellow, bg = palette.none },
	Identifier = { fg = palette.blue, bg = palette.none },
	Function = { fg = palette.yellow, bg = palette.none },
	Statement = { fg = palette.purple, bg = palette.none },
	Conditional = { fg = palette.purple, bg = palette.none },
	Repeat = { fg = palette.purple, bg = palette.none },
	Label = { fg = palette.blue, bg = palette.none },
	Operator = { fg = palette.purple, bg = palette.none },
	Keyword = { fg = palette.purple, bg = palette.none },
	Exception = { fg = palette.purple, bg = palette.none },
	Preproc = { fg = palette.yellow, bg = palette.none },
	Include = { fg = palette.purple, bg = palette.none },
	Define = { fg = palette.purple, bg = palette.none },
	Title = { fg = palette.cyan, bg = palette.none },
	Macro = { fg = palette.purple, bg = palette.none },
	PreCondit = { fg = palette.blue, bg = palette.none },
	Type = { fg = palette.blue, bg = palette.none },
	StorageClass = { fg = palette.blue, bg = palette.none },
	Structure = { fg = palette.yellow, bg = palette.none },
	Typedef = { fg = palette.yellow, bg = palette.none },
	Special = { fg = palette.blue, bg = palette.none },
	SpecialComment = { fg = palette.grey, bg = palette.none },
	Error = { fg = palette.red, bg = palette.none },
	Todo = { fg = palette.purple, bg = palette.none },
	Underlined = { fg = palette.cyan, bg = palette.none },
	Cursor = { fg = palette.none, bg = palette.none },
	ColorColumn = { fg = palette.none, bg = palette.grey_4 },
	CursorLineNr = { fg = palette.yellow_cursorline, bg = palette.none, style = { style.bold } },
	Conceal = { fg = palette.grey, bg = palette.none },
	CursorColumn = { fg = palette.none, bg = palette.grey_4 },
	CursorLine = { fg = palette.none, bg = palette.grey_3 },
	Directory = { fg = palette.blue, bg = palette.none },
	DiffAdd = { fg = palette.grey_3, bg = palette.green },
	DiffChange = { fg = palette.yellow, bg = palette.none },
	DiffDelete = { fg = palette.grey_3, bg = palette.red },
	DiffText = { fg = palette.grey_3, bg = palette.yellow },
	ErrorMsg = { fg = palette.red, bg = palette.none },
	VertSplit = { fg = palette.grey_4, bg = palette.none },
	Folded = { fg = palette.grey, bg = palette.none },
	FoldColumn = { fg = palette.none, bg = palette.none },
	IncSearch = { fg = palette.yellow, bg = palette.grey },
	LineNr = { fg = palette.grey_1, bg = palette.none },
	NonText = { fg = palette.grey_1, bg = palette.none },
	Pmenu = { fg = palette.fg, bg = palette.black_1 },
	PmenuSel = { fg = palette.none, bg = palette.grey_4 },
	PmenuSbar = { fg = palette.none, bg = palette.grey_3 },
	PmenuThumb = { fg = palette.none, bg = palette.fg },
	Question = { fg = palette.purple, bg = palette.none },
	QuickFixLine = { fg = palette.grey_3, bg = palette.yellow },
	Search = { fg = palette.grey_3, bg = palette.yellow },
	SignColumn = { fg = palette.bg, bg = palette.bg },
	SpecialKey = { fg = palette.grey_1, bg = palette.none },
	SpellBad = { fg = palette.red, bg = palette.none },
	SpellCap = { fg = palette.yellow, bg = palette.none },
	SpellLocal = { fg = palette.yellow, bg = palette.none },
	SpellRare = { fg = palette.yellow, bg = palette.none },
	StatusLine = { fg = palette.fg, bg = palette.bg },
	StatusLineNC = { fg = palette.grey, bg = palette.none },
	StatusLineTerm = { fg = palette.fg, bg = palette.bg },
	StatusLineTermNC = { fg = palette.grey_4, bg = palette.none },
	TabLine = { fg = palette.grey, bg = palette.none },
	TabLineSel = { fg = palette.fg, bg = palette.none },
	TabLineFill = { fg = palette.none, bg = palette.grey_3 },
	Terminal = { fg = palette.fg, bg = palette.grey_3 },
	Visual = { fg = palette.none, bg = palette.grey_5 },
	VisualNOS = { fg = palette.grey_5, bg = palette.none },
	WarningMsg = { fg = palette.yellow, bg = palette.none },
	WildMenu = { fg = palette.grey_3, bg = palette.blue },
	EndOfBuffer = { fg = palette.bg, bg = palette.none },
	FloatBorder = { bg = palette.none },
	MatchParen = { fg = palette.none, bg = palette.grey_5 },
}

theme.aerial = {
	AerialLine = { fg = palette.black_1, bg = palette.purple_highlight },
}

theme.bufferline = {
	-- BufferLineFill = { fg = palette.grey_8, bg = palette.grey_4 },
	BufferLineFill = { fg = palette.bg_2, bg = palette.bg_2 },
	-- BufferLineBackground = { fg = palette.grey_8, bg = palette.grey_4 },
	BufferLineBackground = { fg = palette.fg_1, bg = palette.bg_1 }, -- buffer that not shown in window
	-- BufferLineBufferVisible = { fg = palette.fg, bg = palette.bg },
	BufferLineBufferVisible = { fg = palette.fg, bg = palette.bg_1 }, -- buffer that are visible
	BufferLineBufferSelected = { fg = palette.purple, bg = palette.bg, style = { style.bold, style.italic } },
	BufferLineTab = { fg = palette.fg, bg = palette.bg_1 },
	-- BufferLineTabSelected = { fg = palette.bg, bg = palette.bg },
	-- BufferLineTabClose = { fg = palette.bg, bg = palette.bg },
	BufferLineIndicatorSelected = { fg = palette.blue_1, bg = palette.bg },

	BufferLineSeparator = { fg = palette.bg, bg = palette.bg },
	BufferLineSeparatorVisible = { fg = palette.bg, bg = palette.bg },
	BufferLineSeparatorSelected = { fg = palette.bg, bg = palette.bg },

	BufferLineCloseButton = { fg = palette.grey_8, bg = palette.bg_2 },
	BufferLineCloseButtonVisible = { fg = palette.grey_4, bg = palette.bg_1 },
	BufferLineCloseButtonSelected = { fg = palette.grey_10, bg = palette.bg },
	-- BufferLineModified = { fg = palette.red_4, bg = palette.grey_4 },
	-- BufferLineModifiedVisible = { fg = palette.fg, bg = palette.bg },
	-- BufferLineModifiedSelected = { fg = palette.green_2, bg = palette.bg },
	BufferLineError = { fg = palette.red_1, bg = palette.red_1 },
	BufferLineErrorDiagnostic = { fg = palette.red_1, bg = palette.red_1 },
	BufferLineDevIconLuaInactive = { fg = palette.none, bg = palette.bg_1 },
	BufferLineNeotree = { fg = palette.unlisted, bg = palette.none, style = { style.bold, style.italic } },
	BufferLineAerial = { fg = palette.unlisted, bg = palette.none, style = { style.bold, style.italic } },
}

utils.set_theme(theme.base)
utils.set_theme(theme.aerial)
utils.set_theme(theme.bufferline)
