[general]
import = ["/home/benjmanxd/.config/alacritty/font.toml", "/home/benjmanxd/.config/alacritty/mapping.toml", "/home/benjmanxd/.config/assets/theme/alacritty/sweetpastel.toml"]
live_config_reload = true

[cursor]
# custom_cursor_colors = true
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }

[env]
EDITOR = "nvim"
TERM = "alacritty"
VISUAL = "nvim"

[terminal.shell]
program = "zsh"

[window]
opacity = 0.9
# dimensions = { columns = 189, lines = 40 }
padding = { x = 3, y = 4 }
# position = { x = 10, y= 10 }
decorations = "Full"
startup_mode = "Windowed"
class = { general = "Alacritty", instance = "Alacritty" }

[scrolling]
history = 10000
multiplier = 3
