local vg = vim.g
vg.mapleader = " "
vg.maplocalleader = " "

local vo = vim.opt
local vf = vim.fn
vo.backup = false
vo.swapfile = false
vo.undofile = true
vo.writebackup = false
vo.ruler = true
vo.number = true
vo.relativenumber = true
vo.showmode = false
vo.mouse = "a"
vo.wrap = false
vo.background = "dark"
vo.splitbelow = true
vo.splitright = true
--vo.cmdheight = 2
vo.swapfile = false
vo.cursorline = true
vo.cursorcolumn = true
vo.smartindent = true
vo.autoindent = true
vo.shiftwidth = 2
vo.tabstop = 2
vo.expandtab = true
vo.linebreak = true
vo.showtabline = 2
vo.laststatus = 3
--vo.scrolloff = 8
vo.sidescrolloff = 8
vo.encoding = "utf-8"
vo.fileencoding = "utf-8"
vo.clipboard = "unnamedplus"
vo.ignorecase = true
vo.signcolumn = "yes"
vo.guifont = "monospace:h17"
vo.termguicolors = true
vo.completeopt = { "menu", "menuone", "noselect" }
vo.shortmess:append("c")
vo.backupdir = vf.expand("~") .. "/.nvim/backups"
vo.undodir = vf.expand("~") .. "/.nvim/undos"
-- vo.winborder = "rounded"
