vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.writebackup = false
vim.opt.ruler = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.showmode = false
vim.opt.mouse = "a"
vim.opt.wrap = false
vim.opt.background = "dark"
vim.opt.splitbelow = true
vim.opt.splitright = true
--vim.opt.cmdheight = 2
vim.opt.swapfile = false
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.expandtab = true
vim.opt.showtabline = 2
vim.opt.laststatus = 3
--vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.encoding = "utf-8"
vim.opt.fileencoding = "utf-8"
vim.opt.clipboard = "unnamedplus"
vim.opt.ignorecase = true
vim.opt.signcolumn = "yes"
vim.opt.guifont = "monospace:h17"
vim.opt.termguicolors = true
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.shortmess:append("c")
vim.opt.backupdir = vim.fn.expand("~") .. "/.nvim/backups"
vim.opt.undodir = vim.fn.expand("~") .. "/.nvim/undos"
