require("main.general.plugins")
require("main.general.commands")
require("main.general.options")
require("main.general.keymaps")
require("main.lualine")
require("main.theme")
require("main.devicons")
require("main.cmp")
require("main.lsp_config")
require("main.illuminate")
require("main.goto_preview")
require("main.telescope")
require("main.bufferline")
require("main.toggleterm")
require("main.autopair")
require("main.neotree")
require("main.treesitter")
-- NOTE: currently disable aerial since neotree also supports document symbols
-- require("main.aerial")
require("main.alpha")
require("main.whichkey")
require("main.comment")
require("main.indent")
require("main.colorizer")
require("main.todo_comment")
require("main.rest")
require("main.harpoon")
