require("general.options")
require("general.lazy")
require("general.theme")
require("general.commands")
require("general.keymaps")
--require("plugins.illuminate")
--require("plugins.template")
-- NOTE: currently disable aerial since neotree also supports document symbols
-- require("plugins.aerial")
-- require("plugins.rest")
-- require("plugins.harpoon")
