#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey playerctld

## xrandr setting
xrandr --output DP-1 --brightness 0.8
xrandr --output HDMI-1 --brightness 0.8
xrandr --output DP-1 --left-of HDMI-1

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## wallpaper
feh --bg-fill ~/.config/assets/wallpaper/current_wallpaper.jpg

## Start Compositing Manager
exec picom &

## Launch Polybar
killall -q polybar
polybar -q main -c ~/.config/polybar/config.ini &

## Notification Daemon
exec dunst &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## player control daemon
exec playerctld daemon

## spotify_player daemon
$HOME/.cargo/bin/spotify_player -d

## Lock screen service
#systemctl enable betterlockscreen@benjmanxd

## Launch nordvpn service
#systemctl enable nordvpnd.service
#systemctl start nordvpnd.service

## Launch fcitx
# fcitx -d
